# .circleci/config.yml
version: 2
jobs:
  build:
    macos:
      xcode: "9.3.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run:
          name: Carthage
          command: carthage update --platform iOS --cache-builds
  unit-tests:
    macos:
      xcode: "9.3.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - run:
          name: Build and run unit tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: templateTests

  ui-tests:
    macos:
      xcode: "9.3.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - run:
          name: Build and run UI tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: templateUITests

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
      - ui-tests:
          requires:
            - build