version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          name: Run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: templateTests

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test