# .circleci/config.yml
version: 2
dependencies:
  override:
    - bin/bootstrap-if-needed
  cache_directories:
    - "Carthage"
jobs:
  build-and-test:
    macos:
      xcode: "9.3.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - run:
          name: Carthage
          command: bin/bootstrap-if-needed
      - checkout
      - run:
          name: Build and run unit tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: templateTests
      - run:
          name: Build and run UI tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: templateUITests

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: output

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test